version: 2

jobs:
  docker:
    - image: circleci/python:3.6.10
  
  working_directory: ~/repo
    
  steps:
    - checkout
    
    - restore_cache:  # ensure this step occurs *before* installing dependencies
          keys:
          - v1-dependencies-{{ checksum "requirements.txt"}}
          - v1-dependencies-
          
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          make install

    - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt"}}
    - run:
        name: run lint 
        command: |
          source ./venv/bin/activate
          make lint